#!/bin/bash
# 
# paconfig.sh
# 
# Palo alto setup script
# 
# Bennett Riegel
# March 2025

printf "Starting housemd script\n"

# get team ip
printf "Enter team IP number should be between (21-40): "
read team

echo "set cli scripting-mode on" > palolog.txt
echo "configure" >> palolog.txt
echo "set address public-fedora ip-netmask 172.25.$team.39" >> palolog.txt
echo "set address public-splunk ip-netmask 172.25.$team.9" >> palolog.txt
echo "set address public-centos ip-netmask 172.25.$team.11" >> palolog.txt
echo "set address public-debian ip-netmask 172.25.$team.20" >> palolog.txt
echo "set address public-ubuntu-web ip-netmask 172.25.$team.23" >> palolog.txt
echo "set address public-windows-server ip-netmask 172.25.$team.27" >> palolog.txt
echo "set address public-windows-docker ip-netmask 172.25.$team.97" >> palolog.txt
echo "set address public-win10 ip-netmask 172.31.$team.5" >> palolog.txt
echo "set address public-ubuntu-wkst ip-netmask 172.25.$team.111" >> palolog.txt
echo "set address this-fw ip-netmask 172.31.$team.2" >> palolog.txt
echo "set address this-fw2 ip-netmask 172.25.$team.150" >> palolog.txt

# Set the management interface to ONLY 172.20.242.150
echo "set deviceconfig system ip-address 172.20.242.150 netmask 255.255.255.0 default-gateway 172.20.242.1" >> palolog.txt

# Restrict administrative management to HTTPS only
echo "set deviceconfig system service disable-ssh yes disable-http yes disable-telnet yes" >> palolog.txt

cat ./paconfig.txt >> palolog.txt
cp ./paconfig.txt ./backup-paconfig.txt
mv palolog.txt paconfig.txt
echo "commit" >> paconfig.txt


ssh -T -o HostKeyAlgorithms=+ssh-rsa -o PubKeyAuthentication=no -o PasswordAuthentication=yes admin@172.20.242.150 < ./paconfig.txt

cp ./paconfig.txt ./ran.txt
mv ./backup-paconfig.txt ./paconfig.txt

exit 0
